BASE_URL = 'https://www.standwithcrypto.org/'

VALID_POLITICAL_AFFILIATIONS = ['REPUBLICAN', 'DEMOCRAT', 'INDEPENDENT']
VALID_ROLES = ['CONGRESS', 'SENATE', 'VICE_PRESIDENT', 'PRESIDENT']
VALID_STATUSES = ['RUNNING_FOR', 'HELD']